### ISSUE TITLE
Cannot instantiate multiple listeners from a single application

### ISSUE THREAD

**Issue by ziopio** [eproxus/kraft#8]
Hello :D
I am currently developing a super secret saas (guess what) that needs different http&https services with different SSL options.
1 for http port 80
1 for web UI https port 443
1 for the device API https + mutual TLS
I noticed you use the app name as cowboy listener name and the kraft code also expects such atom to be a real app.
code:lib_dir() is called on the atom, so if a provide #{app => something} to kraft:start(), it does not work.
https://github.com/eproxus/kraft/blob/1e171017dabbd56109837cff31d763fdac4ecd2b/src/kraft_dev.erl#L45
Currently I can work around it giving app names of different apps installed with the release, but that is fundamentally wrong.
With cowboy I can have multiple listeners but kraft seams limited by design to just one per application.
How should I overcome this?

**Comment by ziopio** [comment]
Hello, after the latest commits is possible to start multiple listeners per app, but this breaks the routes.
I bet this persistent term is fetched on demand and since you set it per app name a second listener overwrites the term.
https://github.com/eproxus/kraft/blob/3ae440b0b996f8178d4445fdafe9c10195843f44/src/kraft_instance.erl#L40C5-L40C5

Adding the `make_ref() ` there solves the issue.
I can take care of it in a PR.
``` erlang
    DispatchName = {kraft_dispatch, App, make_ref()},
    persistent_term:put(DispatchName, Dispatch),
```

**Comment by eproxus** [comment]
Ah, yes of course. Is the multiple listeners API working out well for you? If so, I’d like to merge it into `main`.

**Comment by ziopio** [comment]
Ok, I'll try that out
